version: '3.8'
services:
  mlflow:
    image: cr.fly.io/mlflow:2.9.1
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root /mlflow/mlruns
