name: Retrain and Register Model

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 0' # weekly on Sunday at 03:00 UTC

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure MLflow environment
        run: |
          mkdir -p ${{ github.workspace }}/mlruns
          echo "MLFLOW_TRACKING_URI=file:${{ github.workspace }}/mlruns" >> $GITHUB_ENV

      - name: Run retraining script
        env:
          MLFLOW_TRACKING_URI: ${{ github.workspace }}/mlruns
        run: |
          python retrain_model.py

      - name: Upload mlruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns
